import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Brain, Wand2, BarChart3, CheckSquare, Plug, Shield,
  ArrowRight, ChevronRight, Star, TrendingUp, Zap, Target
} from "lucide-react";

const FEATURES = [
  { icon: <Wand2 size={20} />, title: "AI Campaign Designer", desc: "Go from goal to full campaign blueprint in 60 seconds. Strategy, channels, audiences, budgets, and assets — all generated by AI." },
  { icon: <Brain size={20} />, title: "Customer Intelligence", desc: "SPARK surfaces dormant leads, high-intent visitors, and upsell opportunities from your CRM and analytics data automatically." },
  { icon: <BarChart3 size={20} />, title: "Channel Workbenches", desc: "Dedicated command centres for PPC, SEO, Social, CRM, Messaging, and Creative — all linked to your campaigns." },
  { icon: <CheckSquare size={20} />, title: "Approval Workflows", desc: "Enterprise-grade approval flows for campaigns, budgets, assets, and AI actions. Every decision has a paper trail." },
  { icon: <Plug size={20} />, title: "Integration Marketplace", desc: "Connect Google Ads, Meta, HubSpot, Salesforce, LinkedIn, Mailchimp, Canva and 20+ platforms with one click." },
  { icon: <Shield size={20} />, title: "Governance & RBAC", desc: "Role-based access control, brand guardrails, audit logs, and autonomous action controls — built for enterprise teams." },
];

const STATS = [
  { value: "3.2x", label: "More qualified leads vs. manual campaigns" },
  { value: "70%", label: "Reduction in campaign planning time" },
  { value: "4.2x", label: "Average ROAS across active campaigns" },
  { value: "500+", label: "Marketing teams using SPARK AI" },
];

const TESTIMONIALS = [
  { name: "Marcus Feld", title: "Head of Marketing, Scale.io", quote: "SPARK AI replaced 3 separate tools and 2 agency retainers. Our campaigns are now better coordinated, faster to launch, and significantly cheaper per qualified lead." },
  { name: "Amanda Chow", title: "CMO, NexPath Group", quote: "The Customer Intelligence module found 312 dormant leads in our CRM we'd completely forgotten about. One reactivation campaign generated $140K in pipeline in 3 weeks." },
  { name: "Rajan Mehta", title: "Growth Director, Foundry Labs", quote: "I've used HubSpot, Salesforce, and a dozen MarTech tools. SPARK AI is the first platform that actually thinks like a marketer, not a developer." },
];

export default function Landing() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Nav */}
      <nav className="fixed top-0 inset-x-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-md bg-primary flex items-center justify-center">
              <span className="text-primary-foreground font-bold text-sm">S</span>
            </div>
            <span className="font-bold text-lg tracking-tight">SPARK <span className="text-primary">AI</span></span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm text-muted-foreground">
            <a href="#features" className="hover:text-foreground transition-colors">Features</a>
            <a href="#how-it-works" className="hover:text-foreground transition-colors">How it works</a>
            <button onClick={() => setLocation("/pricing")} className="hover:text-foreground transition-colors">Pricing</button>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="sm" onClick={() => setLocation("/login")} data-testid="btn-nav-login">Sign In</Button>
            <Button size="sm" onClick={() => setLocation("/login")} data-testid="btn-nav-trial">Start Free Trial</Button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-36 pb-24 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <Badge className="mb-6 border border-primary/40 bg-primary/10 text-primary" variant="outline">
            <Zap size={12} className="mr-1" /> AI-Powered Marketing Intelligence
          </Badge>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.05] mb-6">
            Your AI Marketing<br />
            <span className="bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent">
              Command Centre
            </span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed">
            Plan campaigns, activate channels, approve decisions, and report results — all in one intelligent platform. From goal to blueprint in 60 seconds.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Button size="lg" onClick={() => setLocation("/login")} className="gap-2" data-testid="btn-hero-trial">
              Start Free Trial <ArrowRight size={16} />
            </Button>
            <Button size="lg" variant="outline" onClick={() => setLocation("/login")} data-testid="btn-hero-demo">
              View Live Demo
            </Button>
          </div>
          <p className="mt-4 text-xs text-muted-foreground">No credit card required. 14-day free trial.</p>
        </div>
      </section>

      {/* Stats */}
      <section className="py-16 border-y border-border bg-card/50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {STATS.map((s) => (
              <div key={s.value} className="text-center" data-testid={`stat-${s.value}`}>
                <p className="text-4xl font-bold text-primary mb-2">{s.value}</p>
                <p className="text-sm text-muted-foreground leading-tight">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4 border-primary/40 text-primary">Platform</Badge>
            <h2 className="text-4xl font-bold mb-4">Everything your marketing team needs</h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">One platform. Every channel. Full intelligence.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((f) => (
              <Card key={f.title} className="border-border/60 bg-card/60 hover:border-primary/40 transition-colors" data-testid={`feature-card-${f.title.toLowerCase().replace(/\s/g, "-")}`}>
                <CardContent className="p-6">
                  <div className="w-10 h-10 rounded-lg bg-primary/15 text-primary flex items-center justify-center mb-4">
                    {f.icon}
                  </div>
                  <h3 className="font-semibold mb-2">{f.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-24 px-6 bg-card/30 border-y border-border">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4 border-primary/40 text-primary">Workflow</Badge>
            <h2 className="text-4xl font-bold mb-4">From goal to launch in minutes</h2>
          </div>
          <div className="grid md:grid-cols-4 gap-6">
            {[
              { step: "01", icon: <Target size={20} />, title: "Set your goal", desc: "Define your campaign objective, product, audience, and budget." },
              { step: "02", icon: <Brain size={20} />, title: "SPARK generates blueprint", desc: "AI creates your full campaign strategy, channel plan, and asset requirements." },
              { step: "03", icon: <CheckSquare size={20} />, title: "Approve and activate", desc: "Review, edit, submit for approval, and launch across all channels." },
              { step: "04", icon: <TrendingUp size={20} />, title: "Optimise with AI", desc: "SPARK monitors performance and surfaces recommendations daily." },
            ].map((s) => (
              <div key={s.step} className="text-center" data-testid={`step-${s.step}`}>
                <div className="w-12 h-12 rounded-full bg-primary/15 text-primary flex items-center justify-center mx-auto mb-4">
                  {s.icon}
                </div>
                <p className="text-xs font-bold text-primary mb-1">{s.step}</p>
                <h3 className="font-semibold mb-2">{s.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Trusted by growth-focused teams</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
              <Card key={t.name} className="border-border/60 bg-card/60" data-testid={`testimonial-${t.name.toLowerCase().replace(/\s/g, "-")}`}>
                <CardContent className="p-6">
                  <div className="flex gap-1 mb-4">
                    {[1,2,3,4,5].map((i) => <Star key={i} size={14} className="fill-primary text-primary" />)}
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed mb-4">"{t.quote}"</p>
                  <div>
                    <p className="text-sm font-semibold">{t.name}</p>
                    <p className="text-xs text-muted-foreground">{t.title}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 border-t border-border bg-card/30">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-4xl font-bold mb-4">Ready to run smarter campaigns?</h2>
          <p className="text-muted-foreground text-lg mb-8">Join 500+ teams using SPARK AI to plan, launch, and optimise multi-channel marketing campaigns.</p>
          <div className="flex flex-wrap justify-center gap-4">
            <Button size="lg" onClick={() => setLocation("/login")} className="gap-2" data-testid="btn-cta-trial">
              Start Free Trial <ArrowRight size={16} />
            </Button>
            <Button size="lg" variant="outline" onClick={() => setLocation("/pricing")} data-testid="btn-cta-pricing">
              View Pricing
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-8 px-6 text-center text-sm text-muted-foreground">
        <p>© 2026 SPARK AI. All rights reserved.</p>
      </footer>
    </div>
  );
}
